### ISSUE TITLE
Define a valid composer.json

### ISSUE THREAD

**Issue by wavyx** [intercom/intercom-php-rewrite#5]
Please define a more complete composer.json as in https://github.com/intercom/intercom-php/blob/master/composer.json
Could be useful to have a dev branch (<> master)

**Comment by abishekrsrikaanth** [comment]
It is not currently on packagist, so is there an alternative way to include into a project and test it?

**Comment by wavyx** [comment]
@bobjflong can you merge the pull request to at least make it compatible with composer git repository.
I just tested in a Symfony 3 project with
`"repositories": [
        {
            "type": "git",
            "url": "https://github.com/wavyx/intercom-php-rewrite"
        }
    ],`
and
`"require": {
        "intercom/intercom-php-rewrite": "dev-master"
    },`
